source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'demo1' do

pod 'AFNetworking'
pod 'SDCycleScrollView'
pod 'UIAlertView-Blocks'
pod 'Fabric'
pod 'Crashlytics'
#pod 'SDWebImage'
pod 'TXScrollLabelView'

pod 'XHTestLibrary'

end

target 'demo1Tests' do

end
