
platform :ios, '8.0'

# 忽略cocoapods里的警告
inhibit_all_warnings!
# 引入cocoapods公有仓库
source 'https://github.com/CocoaPods/Specs.git'
# 引入私有仓库
#source 'http://fengxiaohui@git.ops.com/fengxiaohui/TTTRepo.git'

target 'demo1' do

#公有组件
pod 'AFNetworking'
pod 'UIAlertView-Blocks'
pod 'TXScrollLabelView'
pod 'SDCycleScrollView'
pod 'Fabric'
pod 'Crashlytics'


#私有组件
#pod 'TTTLibrary'
#pod 'TTTLibrary', '~> 0.1.0'
#pod 'TTTLibrary', :path => '~/.cocoapods/repos/TTTRepo/TTTLibrary'
#pod 'TTTLibrary', :git => 'http://fengxiaohui@git.ops.com/fengxiaohui/TTTLibrary.git'

end

target 'demo1Tests' do

end
