source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'demo1' do

pod 'AFNetworking'
pod 'SDCycleScrollView'
pod 'UIAlertView-Blocks'
pod 'Fabric'
pod 'Crashlytics'
#pod 'SDWebImage'

end

target 'demo1Tests' do

end
